CFLAGS = -std=c11 -pedantic -Wall -Werror -D_XOPEN_SOURCE=700

all: clash

clash: clash.o plist.o
        gcc -o clash clash.o plist.o

clash.o: clash.c plist.h
        gcc $(CFLAGS) -c clash.c

plist.o: plist.c plist.h
        gcc $(CFLAGS) -c plist.c

clean:
        rm -f clash clash.o plist.o

.PHONY: all clean